Added missing dependency to SuperClosure
During `Mail::queue()` I've got an exception:

> Fatal error: Class 'SuperClosure\Serializer' not found in /var/www/api/vendor/illuminate/mail/Mailer.php on line 243

It looks like there's a missing dependency to `jeremeamia/superclosure`.